version = 1

[[annotations]]
path = [
    "benches/**.rs",
    "src/**"
]
SPDX-FileCopyrightText = "Rodolphe Bréard"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    "benches/**.txt",
    "Cargo.toml",
    "CHANGELOG.md",
    "deny.toml",
    "README.md",
    "REUSE.toml",
    "rustfmt.toml"
]
SPDX-FileCopyrightText = "Rodolphe Bréard"
SPDX-License-Identifier = "FSFAP"
